### ISSUE TITLE
echarts 5.0 无法使用 echarts-wordcloud

### ISSUE THREAD

**Issue by 462937186** [ecomfe/echarts-wordcloud#106]

**Comment by gregdeane** [comment]
Please update soon to work with v5. We've had to disable word cloud on our site and would like to enable it again.

**Comment by SevenTrap** [comment]
Component series.wordCloud not exists. Load it first.

**Comment by pissang** [comment]
We will update echarts-wordcloud after echarts 5.0.1 is released because there is some dependencies. Sorry about the inconvenience we brought

**Comment by AudreyHep** [comment]
> We will update echarts-wordcloud after echarts 5.0.1 is released because there is some dependencies. Sorry about the inconvenience we brought

How long will it be updated？

**Comment by ONEGISER** [comment]
可不可以让echarts-wordcloud支持到echarts5？

**Comment by ONEGISER** [comment]
I encounter error"n.graphic.setTextStyle is not a function"

**Comment by ONEGISER** [comment]
ok！thank you！why you not release 2.0.0?I builded  by myself with your code!

**Comment by pissang** [comment]
@ONEGISER We will release 2.0.0 after ECharts 5.0.1 release ASAP

**Comment by theBigGavin** [comment]
> Component series.wordCloud not exists. Load it first.

下载dist 下的 echarts-wordcloud.js 文件，加入项目本地直接引用

```
import './echarts-wordcloud.js'
const Echarts = require('echarts')
```

就不再报 series.wordCloud 不存在，要加载的问题了。

但是有新的错误

```
Uncaught TypeError: external_echarts_.helper.createTextStyle is not a function
    at Object.seriesModel.layoutInstance.ondraw (echarts-wordcloud.js:70)
    at HTMLCanvasElement.onWordCloudDrawn (echarts-wordcloud.js:1203)
    at eval (echarts-wordcloud.js:901)
    at Array.some (<anonymous>)
    at sendEvent (echarts-wordcloud.js:898)
    at loop (echarts-wordcloud.js:1077)
    at loopingFunction (echarts-wordcloud.js:1031)
    at loop (echarts-wordcloud.js:1092)
    at loopingFunction (echarts-wordcloud.js:1031)
    at loop (echarts-wordcloud.js:1092)
```

**Comment by pissang** [comment]
echarts 更新了吗

**Comment by gregdeane** [comment]
@pissang It appears that eCharts 5.0.1 [has been released](https://github.com/apache/echarts/releases/tag/5.0.1). Do you have a timeframe for getting WordCloud up and running?

**Comment by pissang** [comment]
@gregdeane wordCloud@2.0.0 works with ECharts@5.0.1.

**Comment by gregdeane** [comment]
@pissang Ah, good to know. Thank you!

**Comment by asd281533890** [comment]
wordCloud@1.1.3 works with ECharts@4.9.0.

**Comment by 462937186** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by aFcFzF** [comment]
import 'echarts-wordcloud/dist/echarts-wordcloud'; 

试试呢
